<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report — {{ $report->answerSheet->student_name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2937; padding: 30px; }
        h1 { font-size: 20px; font-weight: bold; margin-bottom: 4px; }
        .meta { color: #6b7280; font-size: 11px; margin-bottom: 24px; }
        .cards { display: flex; gap: 16px; margin-bottom: 24px; }
        .card { flex: 1; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; text-align: center; }
        .card .label { font-size: 10px; color: #9ca3af; text-transform: uppercase; letter-spacing: 0.05em; }
        .card .value { font-size: 22px; font-weight: bold; margin-top: 4px; }
        .pass { background: #f0fdf4; border-color: #bbf7d0; color: #15803d; }
        .fail { background: #fef2f2; border-color: #fecaca; color: #b91c1c; }
        table { width: 100%; border-collapse: collapse; }
        thead { background: #f9fafb; }
        th { text-align: left; padding: 8px 12px; font-size: 11px; color: #6b7280; border-bottom: 1px solid #e5e7eb; }
        td { padding: 8px 12px; border-bottom: 1px solid #f3f4f6; font-size: 11px; }
        .correct { color: #15803d; font-weight: bold; }
        .wrong { color: #b91c1c; font-weight: bold; }
        .badge-correct { background: #f0fdf4; color: #15803d; padding: 2px 8px; border-radius: 999px; }
        .badge-wrong { background: #fef2f2; color: #b91c1c; padding: 2px 8px; border-radius: 999px; }
        .badge-answer { background: #eef2ff; color: #4338ca; padding: 2px 8px; border-radius: 999px; }
        .footer { margin-top: 24px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>

    <h1>{{ $report->answerSheet->student_name }}</h1>
    <p class="meta">
        Student ID: {{ $report->answerSheet->student_id }} &nbsp;|&nbsp;
        Exam: {{ $report->answerSheet->exam->title }} &nbsp;|&nbsp;
        Date: {{ $report->created_at->format('d M Y') }}
    </p>

    <div class="cards">
        <div class="card">
            <div class="label">Score</div>
            <div class="value">{{ $report->score }} / {{ $report->total_questions }}</div>
        </div>
        <div class="card">
            <div class="label">Percentage</div>
            <div class="value">{{ number_format($report->percentage, 1) }}%</div>
        </div>
        <div class="card {{ $report->passed ? 'pass' : 'fail' }}">
            <div class="label">Result</div>
            <div class="value">{{ $report->passed ? 'Pass' : 'Fail' }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Question</th>
                <th>Your Answer</th>
                <th>Correct Answer</th>
                <th>Result</th>
            </tr>
        </thead>
        <tbody>
            @foreach($report->answerSheet->answers->sortBy('question.question_number') as $answer)
                <tr>
                    <td>Q{{ $answer->question->question_number }}</td>
                    <td>
                        @if($answer->selected_option)
                            <span class="{{ $answer->is_correct ? 'correct' : 'wrong' }}">
                                {{ $answer->selected_option->value }}
                            </span>
                        @else
                            <span style="color:#9ca3af">—</span>
                        @endif
                    </td>
                    <td><span class="badge-answer">{{ $answer->question->correct_option->value }}</span></td>
                    <td>
                        @if($answer->is_correct)
                            <span class="badge-correct">Correct</span>
                        @else
                            <span class="badge-wrong">Wrong</span>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <p class="footer">Generated by MCQ Grader &nbsp;·&nbsp; {{ now()->format('d M Y, H:i') }}</p>

</body>
</html>